version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  sort-results: true

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - dupl

linters-settings:
  goimports:
    local-prefixes: github.com/Hamed0406/gofind
  gocyclo:
    min-complexity: 18
  dupl:
    threshold: 80
  revive:
    severity: warning
    rules:
      - name: blank-imports
        disabled: true
      - name: var-naming
      - name: indent-error-flow
      - name: errorf
      - name: exported
        arguments: ["checkPrivateReceivers"]
  misspell:
    locale: US

issues:
  exclude-use-default: false
  exclude:
    - "G304: Potential file inclusion via variable"
    - "should have comment or be unexported"
  max-same-issues: 0
  max-issues-per-linter: 0

