run:
  go: "1.24"
  timeout: 5m
  tests: true
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters: [gocyclo, cyclop, dupl]

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - unused
    - typecheck
    - gocyclo
    - gofmt
    - misspell
  disable:
    - depguard

linters-settings:
  gocyclo:
    min-complexity: 20
  misspell:
    locale: US
  gofmt:
    simplify: true

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
