version: 2

project_name: gofind

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./cmd/gofind
    binary: gofind
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/Hamed0406/gofind/pkg/version.Version={{.Version}}
    goos: [linux, windows]
    goarch: [amd64, arm64]

archives:
  - id: default
    ids: [cli]  # which build(s) to archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # default formats (Linux will use tar.gz by default)
    formats: ["tar.gz"]
    # Override format just for Windows:
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^(feat(\(.+\))?:)'
    - title: Fixes
      regexp: '^(fix(\(.+\))?:)'
    - title: Chore
      regexp: '^(chore(\(.+\))?:)'
    - title: Docs
      regexp: '^(docs(\(.+\))?:)'
    - title: Tests
      regexp: '^(test(\(.+\))?:)'
  filters:
    exclude:
      - '^ci:'
      - '^build:'
      - '^refactor:'

