name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: go test (${{ matrix.os }}, go ${{ matrix.go }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: ["1.24.x"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Print Go env (debug)
        run: |
          go version
          go env
        shell: bash

      - name: Check tidy (must be clean)
        run: |
          set -euxo pipefail
          go mod tidy
          if ! git diff --quiet -- go.mod go.sum; then
            echo "::error::go.mod/go.sum changed after 'go mod tidy'. Commit the result."
            git --no-pager diff -- go.mod go.sum
            exit 1
          fi
        shell: bash

      - name: Vet
        run: go vet ./...

      - name: Build CLI
        run: go build -v ./cmd/gofind

      - name: Test with race + coverage (verbose)
        run: |
          set -euxo pipefail
          go test ./... -race -coverprofile=coverage.out -covermode=atomic -v
        shell: bash

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}.out
          path: coverage.out

  lint:
    name: golangci-lint (from source)
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_LOG_LEVEL: debug

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go (match go.mod)
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Print Go env (debug)
        run: |
          go version
          go env
        shell: bash

      # Build golangci-lint from source with the same Go toolchain -> no mismatch
      - name: Install golangci-lint (from source)
        run: |
          set -euxo pipefail
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
          which golangci-lint || echo "golangci-lint not in PATH; add GOPATH/bin explicitly next step"
        shell: bash

      - name: Run golangci-lint (verbose)
        run: |
          set -euxo pipefail
          "$(go env GOPATH)/bin/golangci-lint" version
          "$(go env GOPATH)/bin/golangci-lint" run --timeout=5m --verbose ./...
        shell: bash
