name: release
on:
  push:
    tags: [ 'v*.*.*' ]   # run only when pushing a version tag like v0.1.0

permissions:
  contents: write   # allow creating GitHub Releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # required for changelog & tag detection

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      # ✅ Use the official GoReleaser action instead of "run goreleaser"
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest   # or pin e.g. v2.3.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

