name: release
on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write   # create GitHub Releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # required for changelog & tag detection

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      # ✅ Use the official action to install & run GoReleaser
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.3.2    # or 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

